/*
  Generates pseudo-random numbers from a uniform distribution
  using the linear congruence algorithm. A pesudo-random number
  in the interval [0.0, 1.0] can be generated by taking an integer
  number from the interval allowed by the machine, i.e. S = 2^N - 1
  where R is the number of bits used to represent an integer.
  The random number is the ratio R = I / S where I is an integer
  in S. To generate a series of random numbers we use the linear
  congruence generator (LCG)

                     I(i + 1) = (aI(i) + b) % m

  where the multiplier a, the increment b and the modulo m are
  constant integers, m being the modulo, and i is the step index.
  The main function prints the period T, that is the number of steps
  after which the random number repeats itself. A user may want a
  long series of pseudo-random numbers, therefore the modulo should
  be large since T <= m.
*/
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#define EXIT_SUCCESS 0
#define EXIT_FAILURE -9
#define MAX_M 1000

typedef long int RANDOM_TYPE;

int main(void) {
  long int i, j, successFlag;
  RANDOM_TYPE a, b, m, seed , randomNumber , randomStore [MAX_M + 1];
  printf ("Enter the multiplier a:\n");
  scanf ("%ld", &a);
  printf ("Enter the increment b:\n");
  scanf ("%ld", &b);
  printf ("Enter the modulo m:\n");
  scanf ("%ld", &m);
  seed = a;
  seed = seed % m;
  printf ("a = %ld b = %ld m = %ld I(0) = %ld\n", a, b, m, seed );
  randomNumber = seed;
  randomStore [0] = randomNumber;
  if (m > MAX_M) {
    printf ("Error: m is too large.\n");
    exit(EXIT_FAILURE );
  }
  i = 1;
  successFlag = 0;
  printf("Random numbers:\n");
  printf("Step %d -> %ld\n", 0, randomNumber);
  while ((i <= m) && (successFlag == 0)) {
    randomNumber = (a * randomNumber + b) % m;
    randomStore[i] = randomNumber;
    printf("Step %d -> %ld\n", i, randomNumber);
    j = 0;
    do {
      if (randomStore[j] == randomNumber) {
        successFlag = 1;
        printf ("Done: period T = %ld\n", i - j);
      }
      j++;
    } while ((j < i) && (randomStore [j - 1] != randomNumber) );
    i++;
  }
  if (successFlag == 1) {
    exit(EXIT_SUCCESS );
  }
  else if (successFlag == 0) {
    printf ("Error (major inconsistency ): T not found .\n");
    exit(EXIT_FAILURE );
  }
}
